name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run Pester test
        shell: pwsh
        run: |
          Invoke-Pester ./test -Output Detailed
          ls /tmp/samplemodule
        env:
          GITHUB_ACTIONS: true
