name: CI

on: 
  push:
    branches:
      - master
    paths:
      - 'src/**/*.psm?1'
      - 'test/**/*.Tests.ps1'
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run Pester test in PowerShell 7.x
        shell: pwsh
        run: |
          Invoke-Pester test -Output Detailed
        env:
          GITHUB_ACTIONS: true

      - name: Run Pester test in PowerShell 5.x
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          Invoke-Pester test -Output Detailed
        env:
          GITHUB_ACTIONS: true
