name: CI

on: 
  push:
    branches:
      - master
    paths:
      - 'src/**/*.psm?1'
      - 'test/**/*.Tests.ps1'
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  ci-pwsh:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run Pester test
        shell: pwsh
        run: |
          Invoke-Pester test -Output Detailed
        env:
          GITHUB_ACTIONS: true

  ci-powershell:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Pester test
        shell: powershell
        run: |
          Invoke-Pester test -Output Detailed
        env:
          GITHUB_ACTIONS: true
