name: Publish PowerShell Module

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["CI"]
    branches: master
    types: [completed]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path ./src/Register-Completion -NuGetApiKey $env:NUGET_KEY -Verbose
