name: Publish PowerShell Module

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/ci.yml
  publish-to-gallery:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          mv ./src ./Register-Completion
          Publish-Module -Path ./Register-Completion -NuGetApiKey $env:NUGET_KEY -Verbose
